name: Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    name: "mon premier job"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 
      uses: actions/setup-node@v1

    - run: npm install

    - run: gulp build

    - uses: actions/upload-artifact@v1
      with:
        name: Monpackage
        path: dest
  test:
    name: "a effacer"
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
    - uses: actions/checkout@v2
