name: Demo

on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Bonjour"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - run: echo "Comment"
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
    - run: echo "allez "
  job4:
    runs-on: ubuntu-latest
    steps:
    - run: echo "vous ?"
